In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
heart_disease = pd.read_csv("./heart-disease.csv")

In [3]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
#create x (all the feature column)
X = heart_disease.drop("target", axis=1)

#Create Y (the  target column)
y = heart_disease["target"]

In [7]:
# Split the data into training and test sets

from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X,y)

In [8]:
#view the data shapes

X_train.shape , X_test.shape , y_train.shape, y_test.shape

((227, 13), (76, 13), (227,), (76,))

In [9]:
#Now let's choose the Model/estimator


Since we are dealing with an classification problem so we can choose, RandomforestClassifier


In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
model = RandomForestClassifier()

In [16]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [18]:
#make prediction

y_predicts = model.predict(X_test)

In [19]:
y_predicts

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [20]:
X_test.loc[206]

age          59.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 206, dtype: float64

In [21]:
heart_disease.loc[206]

age          59.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
target        0.0
Name: 206, dtype: float64

In [22]:
# Make a prediction on a single sample (has to be array)
model.predict(np.array(X_test.loc[206]).reshape(1, -1))

C:\Users\krish\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [23]:
# On the training set
model.score(X_train, y_train)

1.0

In [24]:
# On the test set (unseen)
model.score(X_test, y_test)

0.881578947368421

In [25]:
# Try different numbers of estimators (n_estimators is a hyperparameter you can change)
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.8026315789473685

Trying model with 20 estimators...
Model accruacy on test set: 0.881578947368421

Trying model with 30 estimators...
Model accruacy on test set: 0.8947368421052632

Trying model with 40 estimators...
Model accruacy on test set: 0.8421052631578947

Trying model with 50 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 60 estimators...
Model accruacy on test set: 0.9210526315789473

Trying model with 70 estimators...
Model accruacy on test set: 0.8947368421052632

Trying model with 80 estimators...
Model accruacy on test set: 0.9078947368421053

Trying model with 90 estimators...
Model accruacy on test set: 0.8947368421052632



In [28]:
#saving model for later use

import pickle
pickle.dump(model, open("random_forest_model.pkl","wb"))

In [30]:
#load the save model

loaded_model = pickle.load(open("random_forest_model.pkl","rb"))
loaded_model.predict(np.array(X_test.loc[206]).reshape(1,-1))

C:\Users\krish\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)